### ISSUE TITLE
How to start train in multi-GPU setting？

### ISSUE THREAD

**Issue by JiexingQi** [shuyanzhou/docprompting#6]
Hi, @shuyanzhou ,I run your train code in single-card setting normally. Howerver, when I use the torch.distributed method to start the multi-GPU setting, is get errors:
```
(docprompt) ➜  docprompting git:(main) ✗ ds='conala'
python3 -m torch.distributed.launch --nnodes=1 --nproc_per_node=4 generator/fid/train_reader.py \
    --seed 1996 \
    --train_data data/${ds}/fid.cmd_train.codet5.t10.json \
    --eval_data data/${ds}/fid.cmd_dev.codet5.t10.json \
    --model_name models/generator/codet5-base \                                          
    --per_gpu_batch_size 4 \
    --n_context 10 \
    --name custom.${ds}.fid.codet5.top10 \
    --checkpoint_dir models/generator/ \
    --eval_freq 500 \
    --accumulation_steps 2 \
    --main_port 30843 \
    --total_steps 20000 \
    --warmup_steps 2000
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
Traceback (most recent call last):
  File "generator/fid/train_reader.py", line 227, in <module>
    src.slurm.init_distributed_mode(opt)
  File "/test/qiezi/jxqi/project/iclr_2023_docprompting/docprompting/generator/fid/src/slurm.py", line 107, in init_distributed_mode
    assert params.main_port == -1
AssertionError
Traceback (most recent call last):
  File "generator/fid/train_reader.py", line 227, in <module>
    src.slurm.init_distributed_mode(opt)
  File "/test/qiezi/jxqi/project/iclr_2023_docprompting/docprompting/generator/fid/src/slurm.py", line 107, in init_distributed_mode
    assert params.main_port == -1
AssertionError
Traceback (most recent call last):
  File "generator/fid/train_reader.py", line 227, in <module>
    src.slurm.init_distributed_mode(opt)
  File "/test/qiezi/jxqi/project/iclr_2023_docprompting/docprompting/generator/fid/src/slurm.py", line 107, in init_distributed_mode
    assert params.main_port == -1
AssertionError
Traceback (most recent call last):
  File "generator/fid/train_reader.py", line 227, in <module>
    src.slurm.init_distributed_mode(opt)
  File "/test/qiezi/jxqi/project/iclr_2023_docprompting/docprompting/generator/fid/src/slurm.py", line 107, in init_distributed_mode
    assert params.main_port == -1
AssertionError
Traceback (most recent call last):
  File "/home/xing/miniconda3/envs/docprompt/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xing/miniconda3/envs/docprompt/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xing/miniconda3/envs/docprompt/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/xing/miniconda3/envs/docprompt/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/xing/miniconda3/envs/docprompt/bin/python3', '-u', 'generator/fid/train_reader.py', '--local_rank=3', '--seed', '1996', '--train_data', 'data/conala/fid.cmd_train.codet5.t10.json', '--eval_data', 'data/conala/fid.cmd_dev.codet5.t10.json', '--model_name', 'models/generator/codet5-base', '--per_gpu_batch_size', '4', '--n_context', '10', '--name', 'custom.conala.fid.codet5.top10', '--checkpoint_dir', 'models/generator/', '--eval_freq', '500', '--accumulation_steps', '2', '--main_port', '30843', '--total_steps', '20000', '--warmup_steps', '2000']' returned non-zero exit status 1.
```

**Comment by JiexingQi** [comment]
And on the single-card setting, it get error when evalution:
```
(docprompt) ➜  docprompting git:(main) ✗ ds='conala'
CUDA_VISIBLE_DEVICES="3" python3 generator/fid/train_reader.py \
    --seed 1996 \
    --train_data data/${ds}/fid.cmd_train.codet5.t10.json \
    --eval_data data/${ds}/fid.cmd_dev.codet5.t10.json \
    --model_name models/generator/codet5-base \
    --per_gpu_batch_size 8 \
    --n_context 10 \
    --name custom.${ds}.fid.codet5.top10 \
    --checkpoint_dir models/generator/ \
    --eval_freq 500 \
    --accumulation_steps 2 \
    --main_port 30843 \
    --total_steps 20000 \
    --warmup_steps 2000
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
0 - Number of nodes: 1
0 - Node ID        : 0
0 - Local rank     : 0
0 - Global rank    : 0
0 - World size     : 1
0 - GPUs per node  : 1
0 - Multi-node     : False
0 - Multi-GPU      : False
0 - Hostname       : seccontent-kg-application011164206223.et135
[02/04/2023 11:05:44] {train_reader.py:246} INFO - device type: Tesla V100-SXM2-32GB, memory: 31.74853515625G
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 2
wandb: You chose 'Use an existing W&B account'
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit: 
wandb: Appending key for api.wandb.ai to your netrc file: /test/qiezi/.netrc
wandb: Tracking run with wandb version 0.13.9
wandb: Run data is saved locally in /test/qiezi/jxqi/project/iclr_2023_docprompting/docprompting/wandb/run-20230204_110716-rnb8m0gs
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run incandescent-lamp-1
wandb: ⭐️ View project at https://wandb.ai/jxqi/fid
wandb: 🚀 View run at https://wandb.ai/jxqi/fid/runs/rnb8m0gs
[02/04/2023 11:07:19] {train_reader.py:266} INFO - load the tokenizer from codet5
[02/04/2023 11:07:19] {train_reader.py:295} INFO - init a model from T5
[02/04/2023 11:07:19] {configuration_utils.py:262} INFO - loading configuration file models/generator/codet5-base/config.json
[02/04/2023 11:07:19] {configuration_utils.py:300} INFO - Model config T5Config {
  "_name_or_path": "Salesforce/codet5-base",
  "architectures": [
    "T5ForConditionalGeneration"
  ],
  "bos_token_id": 1,
  "d_ff": 3072,
  "d_kv": 64,
  "d_model": 768,
  "decoder_start_token_id": 0,
  "dropout_rate": 0.1,
  "eos_token_id": 2,
  "feed_forward_proj": "relu",
  "gradient_checkpointing": false,
  "id2label": {
    "0": "LABEL_0"
  },
  "initializer_factor": 1.0,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0
  },
  "layer_norm_epsilon": 1e-06,
  "model_type": "t5",
  "n_positions": 512,
  "num_decoder_layers": 12,
  "num_heads": 12,
  "num_layers": 12,
  "output_past": true,
  "pad_token_id": 0,
  "relative_attention_num_buckets": 32,
  "task_specific_params": {
    "summarization": {
      "early_stopping": true,
      "length_penalty": 2.0,
      "max_length": 200,
      "min_length": 30,
      "no_repeat_ngram_size": 3,
      "num_beams": 4,
      "prefix": "summarize: "
    },
    "translation_en_to_de": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to German: "
    },
    "translation_en_to_fr": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to French: "
    },
    "translation_en_to_ro": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to Romanian: "
    }
  },
  "torch_dtype": "float32",
  "transformers_version": "4.11.3",
  "vocab_size": 32100
}

[02/04/2023 11:07:19] {modeling_utils.py:665} INFO - loading weights file models/generator/codet5-base/pytorch_model.bin
[02/04/2023 11:07:27] {modeling_utils.py:765} INFO - All model checkpoint weights were used when initializing T5ForConditionalGeneration.

[02/04/2023 11:07:27] {modeling_utils.py:768} WARNING - Some weights of T5ForConditionalGeneration were not initialized from the model checkpoint at models/generator/codet5-base and are newly initialized: ['decoder.block.0.layer.1.EncDecAttention.relative_attention_bias.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[02/04/2023 11:07:39] {train_reader.py:348} INFO - Start training
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 266/266 [04:38<00:00,  1.05s/it]
  0%|                                                                                                                                                                                                                    | 0/26 [00:05<?, ?it/s]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 233/266 [04:10<00:35,  1.07s/it]
Traceback (most recent call last):
  File "generator/fid/train_reader.py", line 359, in <module>
    checkpoint_path
  File "generator/fid/train_reader.py", line 84, in train
    dev_em = evaluate(model, eval_dataset, tokenizer, collator, opt)
  File "generator/fid/train_reader.py", line 209, in evaluate
    metric = evaluate_customized(model, dataset, tokenizer, collator, opt, is_bleu=True)
  File "generator/fid/train_reader.py", line 175, in evaluate_customized
    gold = dataset.get_example(idx[k])['target']
IndexError: index 8 is out of bounds for dimension 0 with size 8
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 
wandb: Run history:
wandb:         lr ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb: train_loss ▇██▇▆▇█▆▅▅▅▅▅▅▄▄▄▃▃▂▂▃▂▂▂▂▂▂▁▂▂▂▁▁▁▁▂▂▁▁
wandb: 
wandb: Run summary:
wandb:         lr 1e-05
wandb: train_loss 1.28687
wandb: 
wandb: 🚀 View run incandescent-lamp-1 at: https://wandb.ai/jxqi/fid/runs/rnb8m0gs
wandb: Synced 6 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230204_110716-rnb8m0gs/logs
```

**Comment by shuyanzhou** [comment]
Hi,

My bad, accidentally fix `num_return_sequences=10` as the default while it is supposed to be 1. I have updated it.
https://github.com/shuyanzhou/docprompting/blob/main/generator/fid/src/model.py#L50

For multi-GPU training, the following command works for me -- basically as the error message indicates, the port was an issue
```bash
NGPU=2 python -m torch.distributed.launch --nproc_per_node=2 generator/fid/train_reader.py \
    --seed 1996 \
    --train_data data/${ds}/fid.cmd_train.codet5.t10.json \
    --eval_data data/${ds}/fid.cmd_dev.codet5.t10.json \
    --model_name models/generator/codet5-base \
    --per_gpu_batch_size 4 \
    --n_context 10 \
    --name ${ds}.fid.codet5.top10 \
    --checkpoint_dir models/generator/ \
    --eval_freq 10 \
    --accumulation_steps 2 \
    --total_steps 20000 \
    --warmup_steps 2000
```

**Comment by JiexingQi** [comment]
Thanks a lot @shuyanzhou , I have successfully run your code in single and multiple GPU setting, and the final run command in multi-GPU setting are as follows:

```
ds='conala'
CUDA_VISIBLE_DEVICES="4,5,6,7" NGPU=4 python -m torch.distributed.launch --nproc_per_node=4 generator/fid/train_reader.py \
    --seed 1996 \
    --train_data data/${ds}/fid.cmd_train.codet5.t10.json \
    --eval_data data/${ds}/fid.cmd_dev.codet5.t10.json \
    --model_name models/generator/codet5-base \
    --per_gpu_batch_size 4 \
    --n_context 10 \
    --name ${ds}.fid.codet5.top10 \
    --checkpoint_dir models/generator/ \
    --eval_freq 10 \
    --accumulation_steps 2 \
    --total_steps 20000 \
    --warmup_steps 2000
```

Thanks again.

**Comment by JiexingQi** [comment]
Error still exist, when training 9000 steps, it got error:
```
[02/07/2023 11:24:06] {train_reader.py:101} INFO - 9000 / 20000 |train: 0.057 |evaluation bleu: 31.41|lr: 0.00004
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 533/533 [04:19<00:00,  2.05it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 51/51 [01:56<00:00,  2.29s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 438/533 [04:39<01:00,  1.57it/s]
Traceback (most recent call last):
  File "generator/fid/train_reader.py", line 363, in <module>
    checkpoint_path
  File "generator/fid/train_reader.py", line 88, in train
    dev_em = evaluate(model, eval_dataset, tokenizer, collator, opt)
  File "generator/fid/train_reader.py", line 213, in evaluate
    metric = evaluate_customized(model, dataset, tokenizer, collator, opt, is_bleu=True)
  File "generator/fid/train_reader.py", line 196, in evaluate_customized
    smooth=False, code_tokenize=True)
  File "/home/jxqi/project/text2code/iclr_2023_docprompt/docprompting/dataset_helper/conala/gen_metric.py", line 156, in _bleu
    for line in fh:
  File "/home/jxqi/anaconda3/envs/docprompt/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 368: invalid start byte
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: / 0.012 MB of 0.012 MB uploaded (0.000 MB deduped)
wandb: Run history:
wandb:  eval_bleu ▁▆██▇▇▇▇█▇▇▆▇▆▆▇▇▆
wandb:         lr ▁▁▂▂▃▃▄▄▄▅▅▆▆▇▇▇████████████▇▇▇▇▇▇▇▇▇▇▇▇
wandb: train_loss █▄▄▃▂▂▃▂▃▃▂▂▂▁▂▂▁▁▂▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:
wandb: Run summary:
wandb:  eval_bleu 31.41
wandb:         lr 4e-05
wandb: train_loss 0.03011
wandb:
wandb: 🚀 View run swept-moon-4 at: https://wandb.ai/jxqi/fid/runs/wtm0mb7c
wandb: Synced 6 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230207_100756-wtm0mb7c/logs
```

which python version did you use? I just use python 3.7.9, can you give me more suggestions about it, thank you very much.
